name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  logger: ^2.0.1
  flutter_localizations:
    sdk: flutter
  todos_api:
    path: packages/todos_api
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_repository:
    path: packages/todos_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  mockingjay: ^0.4.0

flutter:
  uses-material-design: true
  generate: true